# Generated by Django 4.2.2 on 2023-10-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_pelicula_valoracion_serie_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productora',
            name='valoracion',
            field=models.URLField(null=True),
        ),
    ]
