# Generated by Django 4.2.2 on 2023-10-16 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0003_productora_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='FotoPerfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fotoPerfil',
                'verbose_name_plural': 'FotosDePerfil',
                'ordering': ('imagen',),
            },
        ),
    ]
