# Generated by Django 4.2.2 on 2023-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productora',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
